### ISSUE TITLE
Yoshis Story Stamp with 360 Controller

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-input-sdl#46] opened 2017-08-04 20:42 UTC
I am not able to perform the stamp attack in yoshis story with the default settings for the 360 controller. Even with changed sensitivity and dead zone it is not working (jumping and pressing down with the control stick)

**Comment by loganmc10** [comment] 2017-08-04 22:50
Is it just Yoshi's story? Does it work in Smash Bros for instance?

**Comment by Papermanzero** [comment] 2017-08-05 09:35
Yes, it is working in every game. 
So using the control stick down is working (also in yoshis story).
But to make the attack you have to press quickly down, which seems does the emulator not recognize.

**Comment by Papermanzero** [comment] 2017-08-05 12:20
Several people have this issue: https://retropie.org.uk/forum/topic/10566/odd-n64-controls-issue/5
Wave Race seems also affected.

**Comment by loganmc10** [comment] 2017-08-05 18:56
huh yep I can confirm this. He doesn't ground pound when I use my Xbox One controller, but it works with the keyboard. Very strange, I'll try and look into this in the coming days.

It works properly in RetroArch so it is probably something wrong with the input plugin

**Comment by loganmc10** [comment] 2017-08-07 02:59
So I believe I know what the problem is here. On the N64, the axis values are represent as a number between -80 and +80.

When I extend the axis all the way down on my Xbox One controller, it registers as "79". I assume these games are looking for a fully extended axis value of 80 to trigger these moves. I just need to spend some time to figure out how to adjust the math to get it to register an "80" when the axis is pressed all the way.

**Comment by loganmc10** [comment] 2017-08-07 03:23
So this is the commit that broke it:

https://github.com/mupen64plus/mupen64plus-input-sdl/commit/618912576642bfa15abc7ddfa025f93ff4d39f00

@richard42 can you look into this? ```ApplyAxisLimits``` is limiting the controller too much, and some things, like the Ground Pound in Yoshi's Story no longer works.

On a related note, this line (and the other similar one) should be re-written:
```
axis_val = ((abs(joy_val) - deadzone) * 80 / range);
```
to:
```
axis_val = round((abs(joy_val) - deadzone) * 80.0 / range);
```

Right now, if the controller reports 79.999999 (which it does), it gets rounded to 79, because its a double being cast to an int. Proper rounding should be applied so it registers as an 80 (or -80)

**Comment by Papermanzero** [comment] 2017-08-26 06:31
Any update? Can you revert the commits, which were a test anyway?

**Comment by richard42** [comment] 2017-09-05 04:14
Papermanzero, can you please test again with the small change that I committed in cf02a74 ?

**Comment by Papermanzero** [comment] 2017-09-08 16:44
Fixed. The plugin is working now. Thanks @richard42

**Closed** 2017-09-08 16:44 UTC
